stages:

  ingest:
    cmd: python -m src.ingest
    outs:
      - data/raw/features.parquet
      - data/raw/targets.parquet

  validate:
    cmd: python -m src.validate
    deps:
      - data/raw/
    outs:
      - data/interim/features_imputadas.parquet
      - data/interim/targets_clean.parquet
    metrics:
      - artifacts/validation_report.json

  features:
    cmd: python -m src.features
    deps:
      - data/interim/
    outs:
      - data/processed/features_processed.parquet
      - data/processed/targets_binary.parquet
      - artifacts/scaler.joblib
      - artifacts/encoder.joblib
      - artifacts/target_enc.joblib
      - artifacts/pipeline.joblib

  train:
    cmd: python -m src.train
    deps:
      - data/processed/
    outs:
      - models/model.pkl
    metrics:
      - artifacts/metrics.json

  evaluate:
    cmd: python -m src.evaluate
    deps:
      - models/model.pkl
      - data/processed/
    outs:
      - artifacts/confusion_matrix.png
      - artifacts/roc_curve.png
      - artifacts/feature_importance_plot.png
      - artifacts/prob_distribution.png
